# Generated by Django 2.2.6 on 2019-11-16 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('numeroTelefono', models.IntegerField()),
                ('correo', models.CharField(max_length=30)),
                ('fechaNacimiento', models.DateField()),
                ('nacionalidad', models.CharField(max_length=20)),
                ('region', models.CharField(max_length=25)),
                ('comuna', models.CharField(max_length=30)),
                ('numeroContacto', models.IntegerField()),
                ('telefonoOficina', models.IntegerField()),
                ('profesion', models.CharField(max_length=20)),
            ],
        ),
    ]
