# Generated by Django 2.2.6 on 2019-11-22 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='galeria')),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='cliente',
            name='numeroContacto',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='numeroTelefono',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefonoOficina',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
