# Generated by Django 3.1.2 on 2020-10-30 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20191122_1913'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoAtencion',
            fields=[
                ('idTipoAtencion', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HistorialMedico',
            fields=[
                ('nroAtencion', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('rutMedico', models.CharField(max_length=10)),
                ('peso', models.CharField(max_length=6)),
                ('temperatura', models.CharField(max_length=6)),
                ('detalleAtencion', models.CharField(max_length=100)),
                ('rutMascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.mascota')),
                ('tipoAtencion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.tipoatencion')),
            ],
        ),
    ]
