# Generated by Django 2.2.6 on 2019-11-20 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20191120_1813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mascota',
            old_name='idMascota',
            new_name='rutMascota',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='correo',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
