# Generated by Django 2.2.7 on 2019-11-21 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20191120_2133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='galeria')),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
    ]
